# Generated by Django 4.1.7 on 2023-03-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'verbose_name': 'Ответный Комментарий', 'verbose_name_plural': 'Ответные Комментарии'},
        ),
    ]
